AsyncFuncAI/deepwiki-open

api/requirements.txt

This fixes the api server startup

Added openai as dependency well otherwise will not start

---

src/app/page.tsx

I made some UI changes:
1. Make main content section height stretch to the available space `flex-1`.
2. Make header width to 100% 
3. When a new page ID selected, scroll new rendered page back to top.

fix: UI changes

---

Dockerfile
README.md
api/main.py
docker-compose.yml
src/app/[owner]/[repo]/page.tsx
src/components/Ask.tsx

Introduce a new environment variable `NEXT_PUBLIC_SERVER_BASE_URL`, so when backend API uses a different port or even have the logic running on another machine, frontend can always talk to backend API.

fix: customized API port

---

api/config.py
api/data_pipeline.py
api/ollama_patch.py
api/rag.py
api/requirements.txt
api/simple_chat.py
src/app/[owner]/[repo]/page.tsx
src/app/page.tsx
src/components/Ask.tsx

Sort of a PoC to make this work with Ollama Client. Currently using `nomic-embed-text` for embedding and `qwen3:8b` for generator so make sure you pull these model first.
I wanted to add some kind of toggle in the FE for switching between OpenAI/Gemini and local Ollama, but I am unfamiliar with React so I set the flag to True in the BE for now.
There are a few TODOs that need addressing to make it backward compatible. But you should be able to use this to generate  the wiki as is. Below is my result.

feat: Adding support for Ollama client

---

README.md

This PR is a minor document correction. `Step X` should be `h4` .

docs: change valid heading size

---

Dockerfile

When pulling a Git repository via the UI, an error occurred because git was not installed in the Docker image:
```
deepwiki-1  | 2025-05-07 07:42:59,159 - api.data_pipeline - ERROR - Failed to create repository structure: An unexpected error occurred: [Errno 2] No such file or directory: 'git'
deepwiki-1  | 2025-05-07 07:42:59,159 - api.simple_chat - ERROR - Error preparing retriever: An unexpected error occurred: [Errno 2] No such file or directory: 'git'
```
This PR adds git to the image to fix repository operations.
See also #20

fix: Add git to docker Image to fix git clone errors

---

Dockerfile
README.kr.md
README.md
README.vi.md
docker-compose.yml
next.config.ts
src/app/api/chat/stream/route.ts

Since we are using API routers for fe, no need to make `SERVER_BASE_URL` exposable to frontend.

chore: Change SERVER_BASE_URL

---

api/data_pipeline.py
api/rag.py
api/simple_chat.py
src/app/[owner]/[repo]/page.tsx
src/app/page.tsx
src/components/Ask.tsx
src/types/repoinfo.tsx
src/types/wiki/wikipage.tsx
src/types/wiki/wikistructure.tsx
src/utils/getRepoUrl.tsx
src/utils/urlDecoder.tsx

Improve url management for including self-hosted gitlab server. 
Issue #26

Feature: Support self-hosted gitlab instance

---

Dockerfile-ollama-local
Ollama-instruction.md

- New file `Dockerfile-ollama-local`
- Updated instruction `Ollama-instruction.md`
It is an All-in-One Dockerfile to put the ollama and Qwen3:1.7b, nomic-embed-text running background with deepwiki.   
Make life easier to deploy standalone.

Add a Dockerfile for ollama-local deployment

---

Dockerfile-ollama-local
Ollama-instruction.md
README.md

- Add automatic architecture detection to `Dockerfile-ollama-local` to support both ARM64 (Apple Silicon) and AMD64
- Add `ARG TARGETARCH` with a default value of arm64 in Dockerfile
- Implement conditional logic to download the appropriate Ollama binary
- Update README with clear instructions for both architectures
- Add troubleshooting guidance for architecture-specific issues
- Maintains compatibility with Intel/AMD systems
- Local repositories can be mounted to `/app/local-repos/my-project` (https://github.com/AsyncFuncAI/deepwiki-open/pull/57#issuecomment-2875244603)
- Follows Docker best practices for cross-architecture support

Enhance Dockerfile for ollama-local with ARM64 (Apple Silicon) detection

---

README.es.md
README.ja.md
README.kr.md
README.md
README.vi.md
README.zh.md

Add multi-language switching functionality to all README documents, making it easy for users to switch between different language versions.

add language switcher to README files

---

src/components/Ask.tsx
src/utils/getRepoUrl.tsx

Ask does not work when the url likes "/{owner}/{repo}?type=gitlab&language=zh" which without the repo_url.
Only need to provide a mock url for resolving the repo info by backend because the repo has been stored when asking.

fix: repo_url is empty when ask but failed

---

README.es.md
README.ja.md
README.kr.md
README.md
README.vi.md
README.zh.md
api/README.md
api/openai_client.py

It took me forever to debug and finally realise from this error:
```
2025-05-23 11:27:18,232 - adalflow.core.embedder - ERROR - Error calling the model: Error code: 401 - {'error': {'message': 'Your authentication token is not from a valid issuer.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_issuer'}}
Batch embedding documents: 100%|█| 2/2 [00:04<00:00,  1.
Batch embedding documents: 100%|█| 2/2 [00:04<00:00,  2.
```
The OpenAI environment variable should be `OPENAI_BASE_URL` and `OPENAI_API_KEY` which are recognised by the OpenAI client. It is used inconsistently here with `OPENAI_API_KEY` and `OPENAI_API_BASE` .

replace environment variable OPENAI_API_BASE with OPENAI_BASE_URL to align with OPENAI standard

---

Ollama-instruction.md
README.md
api/README.md

Add instructions for `OLLAMA_HOST` env variable when using Ollama that is not local.

doc: add env instructions for Ollama if not local

---

src/components/Ask.tsx

This PR addresses [Issue #164](https://github.com/AsyncFuncAI/deepwiki-open/issues/164), where the "Ask" button overlaps the input field, making the end of long questions hard to read.
- Added `pr-32` to the input field for sufficient right padding
- Preserved the position and functionality of the "Ask" button
- Improved usability and visibility when typing long questions
The text at the end of the input would be obscured by the button:
The padding ensures that text is clearly visible even near the end of the input:
Let me know if any adjustments are needed to fit the design standards or if further layout refinements are preferred.

improve: Resolve overlapping "Ask" button and improve input field text visibility

---

api/data_pipeline.py

There's like one place left in the code that uses curl, but everywhere else, `requests` is used. This removes the last bits of that and moves to pure python. `curl` is still left in the container a debugging tool.

chore: removing calls to curl, replacing with requests parity

---

api/api.py
api/config.py
api/config/lang.json
api/simple_chat.py
api/websocket_wiki.py
next.config.ts
src/app/page.tsx
src/components/ConfigurationModal.tsx
src/contexts/LanguageContext.tsx

I've added a language configuration file `lang.config.json` to define selectable languages for content generation.
The API endpoints for chat and wiki caching have been updated to validate the selected language against this configuration. Requests with unsupported languages will now be rejected with an appropriate error message.
Key changes:
- Created `api/config/lang.json` with an initial set of supported languages.
- Modified `api/config.py` to load this configuration.
- Implemented language validation in:
- `api/simple_chat.py` (chat_completions_stream)
- `api/websocket_wiki.py` (handle_websocket_chat)
- `api/api.py` (get_cached_wiki, store_wiki_cache, delete_wiki_cache)

feat: Add language configuration and API validation

---

api/config.py

Remove reduplicate logic in `load_lang_config`, which is included in `load_json_config(file_name)`

feat: lang config loaded by file name

---

src/utils/urlDecoder.tsx

Issue #26 
In the current URL domain extraction logic, the `extractUrlDomain` function failed to correctly include the port number in the returned domain string when processing URLs that contain non-standard (non-default) ports. This led to incomplete or inaccurate domain information in scenarios such as self-hosted GitLab instances, where they might be running on ports other than 80 or 443.

fix: Corrected non-default port extraction for self-hosted gitlab

---

api/main.py

When running the app in debug mode via python -m api.main, the watchfiles module detects changes in the api folder and triggers reloads. However, since logs are written to files within the same folder, each log write causes a file change, resulting in an infinite loop like:
2025-06-12 09:39:40,300 - INFO - watchfiles.main - main.py:308 - 1 change detected
2025-06-12 09:39:40,651 - INFO - watchfiles.main - main.py:308 - 1 change detected
...
To prevent this, we set the log level of watchfiles.main to WARNING, effectively suppressing its own info-level logs that were triggering further reloads.

fix: prevent infinite logging loop caused by log file changes

---

README.md
api/api.py
api/azureai_client.py
api/config.py
api/config/generator.json
api/simple_chat.py
api/websocket_wiki.py
src/app/[owner]/[repo]/page.tsx

Client Implementation and update documentation
Added AzureAIClient for interacting with Azure OpenAI models.
Updated README.md to include Azure OpenAI API key, endpoint, and version setup instructions.
Modified configuration to support Azure as a model provider.
Enhanced chat completion handling to include Azure API calls in websocket and streaming contexts.
Updated generator configuration to define Azure models and their parameters.

feat: integrate Azure OpenAI support

---

api/config/generator.json
api/simple_chat.py
api/websocket_wiki.py

OpenAI's o3 model doesn't support the `top_p` parameter, causing API errors. This PR removes `top_p` from o3's configuration and updates the code to conditionally include parameters only when they exist in the model config.
Also adjusted o3's temperature to 1.0 (the only supported value for this model).

fix: remove unsupported `top_p` parameter for OpenAI o3 model

---

api/data_pipeline.py
src/app/[owner]/[repo]/page.tsx

Some enterprise environments use self-hosted GitHub services. To support these cases, the endpoint has been updated to dynamically use the original repository URL, changing from a fixed "https://api.github.com/repos/" to a flexible domain such as "https://github.company.com/api/v3".

feat: update github api with Enterprise endpoint support

---

.gitignore
api/logging_config.py
api/main.py
docker-compose.yml

In the previous pull request https://github.com/AsyncFuncAI/deepwiki-open/pull/210, it didn't solve the issue, but just ignored it by using the WARNING log level. 
And according to the discussion in https://github.com/encode/uvicorn/discussions/1656 , the only solution is to change the log file's location.

fix: move log file to parent directory to avoid infinite logging loop

---

.gitignore
api/logging_config.py
api/main.py
docker-compose.yml

I am sorry for my previous PR, seems that is not the correct fix, because watcher will watch the current working directory, but we will run `python -m api.main` in the workspace root, so the watcher still detected the changes, `reload_dir` just decided which directory will be reloaded and didn't affect watchers.
This patch has correct fix and didn't change log file's location. 
I tested it and looks good to me.

fix: add IgnoreLogChangeDetectedFilter for logging to ignore changes

---

src/app/globals.css

In this PR provide small styles fix for issue related to unreadable select options in google chrome browser.
When dark theme is enabled, options appear as light gray text on white background which is hard to read and inconsistent with the theme.
I attach also screenshots with select options before and after code changes.
My Google Chrome version is Version 138.0.7204.92 (Official Build) (64-bit)
My OS: Ubuntu 24.04.2 LTS

fix issue with select options background on google chrome browser

---

src/app/[owner]/[repo]/page.tsx

This PR fixes a bug where the "include" mode parameters (included_dirs and included_files) were not being passed from the RepoWikiPage component to the API. This resulted in the include functionality not working at all, as the backend never received the necessary directives.
The Problem
The component at src/app/[owner]/[repo]/page.tsx was not configured to handle include parameters. Specifically:
It did not read included_dirs or included_files from the URL search parameters.
It did not pass these values down to the addTokensToRequestBody function, which builds the payload for the API call.
The Solution
This PR addresses the issue by correctly "plumbing" the include parameters through the component and down to the API request. The changes are as follows:
In RepoWikiPage:
The component now …

fix(repo-page): pass 'include' params to API

---

api/data_pipeline.py

In this PR I provide a fix for accessing bitbucket repository with access token.
It didn't work initially until adding x-token-auth: prefix in URL as suggested in bitbucket token generation page.
Afterwards was able to generate deepwiki for my private bitbucket repository:

fix clone bitbucket with access token

---

src/app/[owner]/[repo]/page.tsx

In this PR I provide fix support for bitbucket and gitlab repository links.
repoType was chosen based on GET param which is "github" by default.
This GET param is changed only when "access token" section repository type is selected, but UI suggest that it's recognized automatically.
therefore when using suggested link for open bitbucket repository (https://bitbucket.org/atlassian/atlaskit) it end with 404 error message that comes from github related condition
Changed code to detect repository type from URL in first place.

fix bitbucket and gitlab repo access

---

api/config.py
api/config/generator.json
api/dashscope_client.py
api/websocket_wiki.py

Dashscope (or 阿里云百炼 in Chinese) is a provider for a series of models, including text-embedding, Qwen, and Deepseek.
This commit helps support Dashscope for both embedding and generation.

support dashscope https://bailian.console.aliyun.com/

---

api/data_pipeline.py

This PR enhances the git cloning performance by adding additional shallow clone options to reduce cloning time and bandwidth usage, especially for large repositories.
Added two optimization flags to the git clone command in the [download_repo](file:///Users/dustyposa/data/open_source/ai/deepwiki-open/api/data_pipeline.py#L57-L126) function:
1. `--single-branch` - Clones only the default branch instead of all branches
2. `--depth=1` - Creates a shallow clone with only the latest commit (already present)
- **Reduced cloning time**: Especially noticeable for large repositories with extensive history
- **Lower bandwidth usage**: Downloads only necessary data
- **Faster CI/CD pipelines**: When dealing with large codebases
- **Reduced disk space usage**: Smaller local repository footprint
The …

Optimize Git Clone Speed with Shallow Clone Options
